version: "3"
services:
  backend:
    build: 
      context: backend
    volumes: 
      - ./backend:/usr/src/app/backend
      - ./.env/config:/usr/src/app/.env/config
  frontend:
    image: abiosoft/caddy
    volumes:
      - ./frontend/Caddyfile:/etc/Caddyfile
      - ./frontend/www:/var/www
      - ./.env/caddy:/root/.caddy
    ports:
      - 2015:2015
    links:
      - backend:backend
